const COLORS = {
    red: "#FFB3B3",
    rose: "#F7B2C4",
    pink: "#FFB6C1",
    blush: "#F4C2C2",
    coral: "#FFB7A5",
    salmon: "#FFB5A7",
    peach: "#FFDAB9",
    apricot: "#FDD5B1",
    orange: "#FFD1A9",
    amber: "#FFE0A3",
    yellow: "#FFF3B0",
    lemon: "#FFFACD",
    cream: "#FFF1C1",
    lime: "#D8F3A5",
    green: "#B7E4C7",
    mint: "#B8E0D2",
    seafoam: "#C7E9D5",
    sage: "#C5D8A4",
    pistachio: "#D4E7B5",
    teal: "#A8DADC",
    aqua: "#B5EAEA",
    cyan: "#B8E3E9",
    sky: "#BDE0FE",
    blue: "#AEC6CF",
    powderBlue: "#B0D4F1",
    periwinkle: "#C3CDE6",
    lavender: "#D8BFD8",
    lilac: "#C8A2C8",
    purple: "#CDB4DB",
    mauve: "#D8A7B1",
    orchid: "#E0BBE4",
    plum: "#D7BDE2",
    magenta: "#E8A8C7",
    beige: "#E8D5B7",
    sand: "#E6D3B3",
    taupe: "#D8C3A5",
    gray: "#D8D8D8",
    blueGray: "#B8C6D1",
    greenGray: "#C3D5C3",
    brown: "#D2B48C",
};

module.exports = {
    COLORS,
};
