//src/constants/otp.js
const OTP_TYPES = {
    VERIFY_ACCOUNT: "VERIFY_ACCOUNT",
    RESET_PASSWORD: "RESET_PASSWORD",
    VERIFY_DEVICE: "VERIFY_DEVICE",
    DELETE_ACCOUNT: "DELETE_ACCOUNT",
    OWNER_ACCEPT_INVITE: "OWNER_ACCEPT_INVITE",
};
module.exports = {
    OTP_TYPES,
};
