// src/constants/verification.js
const VERIFICATION_TYPES = {
    VERIFY_ACCOUNT: "VERIFY_ACCOUNT",
    RESET_PASSWORD: "RESET_PASSWORD",
    VERIFY_DEVICE: "VERIFY_DEVICE",
    DELETE_ACCOUNT: "DELETE_ACCOUNT",
    OWNER_ACCEPT_INVITE: "OWNER_ACCEPT_INVITE",
};
module.exports = {
    VERIFICATION_TYPES,
};
